import "./globals.css";
import { Navbar1 } from "@/components/navbar-01";
import { Footer3 } from "@/components/footer-03";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar1 />
        {children}
        <Footer3 />
      </body>
    </html>
  );
}
